from __future__ import annotations

import argparse
import logging
import signal
import sys
from pathlib import Path

from . import __version__
from .config import ConfigError
from .config import RunnerConfig
from .config import load_config
from .git_ops import GitError
from .git_ops import _git_absolute_path
from .guard import PRESERVED_ENVIRONMENT_VARIABLE_NAMES
from .guard import GuardError
from .guard import render_canonical_script_guard
from .runner import GitPollingRunner

log = logging.getLogger("fetch_runner")


def main(argv: list[str] | None = None) -> int:
    argument_parser = argparse.ArgumentParser(
        prog="fetch-runner",
        description="Poll git branches and run scripts when new commits arrive.",
    )
    argument_parser.add_argument("config", type=Path, nargs="?", help="path to jobs.toml")
    argument_parser.add_argument(
        "--check",
        action="store_true",
        help="validate the config (including every script's guard) and exit",
    )
    argument_parser.add_argument(
        "--print-guard",
        metavar="USER",
        help="print the canonical guard block for USER and exit (for pasting into a new script)",
    )
    argument_parser.add_argument(
        "--print-sudoers",
        action="store_true",
        help=(
            "load the config and print a sudoers fragment for every job whose "
            "run_as user differs from the polling user; exit without running"
        ),
    )
    argument_parser.add_argument(
        "-v",
        "--verbose",
        action="store_true",
        help="enable debug logging",
    )
    argument_parser.add_argument(
        "--version",
        action="version",
        version=f"fetch-runner {__version__}",
    )
    cli_args = argument_parser.parse_args(argv)

    _configure_logging(cli_args.verbose)

    if cli_args.print_guard:
        try:
            sys.stdout.write(render_canonical_script_guard(cli_args.print_guard))
        except GuardError as e:
            print(f"error: {e}", file=sys.stderr)
            return 2
        return 0

    if cli_args.config is None:
        argument_parser.error("config path is required (or use --print-guard)")

    try:
        runner_config = load_config(cli_args.config)
    except ConfigError as e:
        print(f"config error: {e}", file=sys.stderr)
        return 2

    if cli_args.print_sudoers:
        sys.stdout.write(render_sudoers_fragment(runner_config))
        return 0

    if cli_args.check:
        print(
            f"ok: user={runner_config.runtime_user} "
            f"jobs={len(runner_config.jobs)} "
            f"poll={runner_config.poll_interval_seconds}s"
        )
        return 0

    runner = GitPollingRunner(runner_config)

    def _handle_stop_signal(signum, _frame):
        log.info("received signal %s; shutting down", signum)
        runner.request_stop()

    signal.signal(signal.SIGTERM, _handle_stop_signal)
    signal.signal(signal.SIGINT, _handle_stop_signal)
    return runner.run_forever()


def render_sudoers_fragment(runner_config: RunnerConfig) -> str:
    """Return a sudoers fragment authorizing every cross-user job in the config.

    Emits three sections for jobs whose ``run_as`` differs from the polling
    user:

    1. ``Defaults!<script>`` env_keep lines so sudo will preserve the
       ``FETCH_RUNNER_*`` variables when running each deploy script.
    2. ``<polling_user> ALL=(<run_as>) NOPASSWD: <git>`` per unique run_as,
       authorizing the git operations fetch-runner performs against repos
       owned by each run_as user.
    3. ``<polling_user> ALL=(<run_as>) NOPASSWD: <script>`` per unique
       ``(run_as, script)`` pair, authorizing the deploy script itself.

    Jobs whose ``run_as`` already equals the polling user are skipped —
    those run directly, without sudo. Output is deterministic (sorted) so
    re-generating after a config change produces a reviewable diff.
    """
    cross_user_jobs = [
        configured_job
        for configured_job in runner_config.jobs
        if configured_job.run_as_user != runner_config.runtime_user
    ]
    rendered_lines: list[str] = []
    rendered_lines.append(
        "# Generated by `fetch-runner --print-sudoers`. "
        "Install with `visudo -f /etc/sudoers.d/fetch-runner`, root:root mode 0440.\n"
    )
    if not cross_user_jobs:
        rendered_lines.append(
            "# (no jobs in this config use a run_as user different from "
            f"the polling user {runner_config.runtime_user!r}; no sudoers rules needed.)\n"
        )
        return "".join(rendered_lines)

    try:
        git_path = _git_absolute_path()
    except GitError as e:
        raise SystemExit(f"fetch-runner --print-sudoers: cannot resolve git path: {e}") from e

    unique_runas_users = sorted({j.run_as_user for j in cross_user_jobs})
    unique_script_paths = sorted({str(j.script_path) for j in cross_user_jobs})
    unique_runas_and_script_pairs = sorted(
        {(j.run_as_user, str(j.script_path)) for j in cross_user_jobs}
    )
    env_keep_value = " ".join(PRESERVED_ENVIRONMENT_VARIABLE_NAMES)

    rendered_lines.append("\n# Preserve FETCH_RUNNER_* env vars only when running these scripts.\n")
    for script_path in unique_script_paths:
        rendered_lines.append(f'Defaults!{script_path} env_keep += "{env_keep_value}"\n')

    rendered_lines.append(
        "\n# Allow fetch-runner to run git as each run_as user. Repos are owned by\n"
        "# the run_as user, so all git operations cross the privilege boundary here.\n"
    )
    for run_as_user_name in unique_runas_users:
        rendered_lines.append(
            f"{runner_config.runtime_user} ALL=({run_as_user_name}) NOPASSWD: {git_path}\n"
        )

    rendered_lines.append("\n# Allow fetch-runner to run each deploy script as its run_as user.\n")
    for run_as_user_name, script_path in unique_runas_and_script_pairs:
        rendered_lines.append(
            f"{runner_config.runtime_user} ALL=({run_as_user_name}) NOPASSWD: {script_path}\n"
        )
    return "".join(rendered_lines)


def _configure_logging(verbose: bool) -> None:
    logging.basicConfig(
        level=logging.DEBUG if verbose else logging.INFO,
        format="%(asctime)s %(levelname)s %(name)s: %(message)s",
        datefmt="%Y-%m-%dT%H:%M:%S%z",
        stream=sys.stderr,
    )
